# Generated by Django 6.0.5 on 2026-05-11 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=220, unique=True)),
                ('category', models.CharField(choices=[('school', 'School ERP'), ('hospital', 'Hospital'), ('ai', 'AI Platform'), ('church', 'Church'), ('government', 'Government'), ('saas', 'SaaS'), ('mobile', 'Mobile'), ('other', 'Other')], default='other', max_length=32)),
                ('summary', models.CharField(max_length=400)),
                ('description', models.TextField(blank=True)),
                ('stack', models.JSONField(blank=True, default=list)),
                ('image_url', models.URLField(blank=True)),
                ('client_name', models.CharField(blank=True, max_length=200)),
                ('featured', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('completed_at', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['order', '-completed_at', 'title'],
            },
        ),
    ]
